version: '3.8'

services:
  db:
    image: postgres:16
    container_name: sk8path-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: sk8path
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: sk8path-api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=sk8path;Username=postgres;Password=mypassword
    ports:
      - "8080:80"

volumes:
  postgres-data:
